name: backend
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  uno: ^1.1.10
  result_dart: ^1.1.1
  shelf: ^1.4.2
  shelf_modular: ^0.0.1
  postgresql2: ^1.7.0
  redis: ^4.0.0
  # path: ^1.8.0

dev_dependencies:
  flutterando_analysis: ^0.0.2
  mocktail: ^1.0.4
  test: ^1.24.0
